=== Oleh16101982/WorkWithPfile/include/NBU00701.XSD
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="NBU_COMMON.xsd"/>
	<!--===================================================================================================================================================================-->
	<xs:element name="DECLARATION" type="DECLARATION_TYPE">
		<xs:unique name="UNIQ_OWNER">
			<xs:selector xpath="OWNER"/>
			<xs:field xpath="@ROWNUM"/>
		</xs:unique>
		<xs:unique name="UNIQ_GOLOS">
			<xs:selector xpath="PERE_GOLOS"/>
			<xs:field xpath="@ROWNUM"/>
		</xs:unique>
	</xs:element>
	<!--===================================================================================================================================================================-->
	<xs:complexType name="DECLARATION_TYPE">
		<xs:sequence>
			<xs:element name="HEAD" type="DHEAD"/>
			<!-- Актуальна дата, на яку подана інформація INF_DT-->
			<xs:element name="INF_DT" type="DGDate"/>
			<!-- Файл-таблиця (формат PDF). Інформація про власників істотної участі - Перелік (Положення - Глава 4).-->
			<xs:element name="TABLE_PIC" type="xs:base64Binary"/>
			<!-- Файл-схема (формат PDF). Інформація про власників істотної участі - Схематичне зображення (Положення - Глава 4).-->
			<xs:element name="PICTURE" type="xs:base64Binary"/>
			<!--1. Відомості про структуру власності банку. Структура OWNER. Якщо власників кілька, підструктура OWNER повторюється.-->
			<xs:element name="OWNER" type="DECLARBODY_OWNER" maxOccurs="999999"/>
			<!--======================================================================================================-->
			<!--2. Інформація про набуття права голосу. Структура PERE_GOLOS . Якщо записів про набуття права голосу кілька, структура PERE_GOLOS повторюється.-->
			<xs:element name="PERE_GOLOS" type="PERE_GOLOS_TYPE" maxOccurs="999999"/>
			<!--======================================================================================================-->
			<!--3. Відсотки статутного капіталу банку (сума) та кількість голосів (сума). Структура SUM_BANK.-->
			<xs:element name="SUM_BANK" type="GOLOS_TYPE"/>
			<!--======================================================================================================-->
			<!--4. Інформація про керівника банку, що підписав анкету та виконавця. Структура MAN_BANK.-->
			<xs:element name="MAN_BANK" type="MAN_BANK_TYPE" nillable="false"/>
		</xs:sequence>
	</xs:complexType>
	<!--===================================================================================================================================================================-->
	<xs:complexType name="DECLARBODY_OWNER">
		<xs:sequence>
			<!-- Структура OWNER. -->
			<!--1.1	Тип учасника - набуває значень: 1-ЮрОсоба, 2-ФізОсоба-->
			<xs:element name="OWNER_TYPE">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!--1.2 Код та повне найменування юр.особи або ПІБ фіз.особи -->
			<xs:element name="OWNER_NAZVA" type="NAZVA_TYPE"/>
			<!--1.3 Ознака особи. Набуває значень:
                  20 – власник істотної участі в банку;
                  21 – асоційована особа власника істотної участі в банку;
                  50 – особа співвласник;
                  51 - асоційована особа співвласника;
                  60 – особа, через яку здійснюється опосередковане володіння участю в банку;
                  61 - асоційована особа особи, через яку здійснюється опосередковане володіння участю в банку;
                 -->
			<xs:element name="OWNER_OZN">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:enumeration value="20"/>
						<xs:enumeration value="21"/>
						<xs:enumeration value="50"/>
						<xs:enumeration value="51"/>
						<xs:enumeration value="60"/>
						<xs:enumeration value="61"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!--1.4 Посада фіз.особи -->
			<xs:element name="OWNER_POS" type="xs:string" nillable="true"/>
			<!--1.5.Місцезнаходження юр.особи або місце проживання фіз.особи (підструктура OWNER_ADR структури OWNER) -->
			<xs:element name="OWNER_ADR" type="ADR_TYPE"/>
			<!--1.6 Відомості про документ, що посвідчує фізичну особу (паспорт) (підструктура OWNER_PASS структури OWNER) -->
			<xs:element name="OWNER_PASS" type="PASS_TYPE" nillable="true"/>
			<!--1.7 Дата народження. Зазначається для фізичної особи -->
			<xs:element name="OWNER_DATE" type="DGDate" nillable="true"/>
			<!--1.8.Державний орган, який здійснив реєстрацію (для іноземних юридичних осіб) -->
			<xs:element name="OWNER_DORG" type="xs:string" nillable="true"/>
			<!--1.9 Пряма участь (підструктура PR_UCH структури OWNER)-->
			<xs:element name="PR_UCH" type="UCHAST_TYPE" nillable="true"/>
			<!--1.10.Опосередкована участь (підструктура OPR_UCH структури OWNER)-->
			<xs:element name="OPR_UCH" type="UCHAST_TYPE" nillable="true"/>
			<!--1.11. Набуте право голосу (підструктура GOL_UCH структури OWNER)-->
			<xs:element name="GOL_UCH" type="GOLOS_TYPE" nillable="true"/>
			<!--1.12. Загальний відсоток у статутному капіталі та загальна кількість голосів (підструктура ZAG_UCH структури OWNER)-->
			<xs:element name="ZAG_UCH" type="GOLOS_TYPE"/>
		</xs:sequence>
		<xs:attribute name="ROWNUM" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="999999"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ID_OSOBU">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:pattern value="([0-9]{1,10})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LNAME">
		<xs:restriction base="xs:string">
			<xs:maxLength value="254"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NAME">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OTCHESTVO">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="COD_STR">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="COD_INDEX">
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="99999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PUNKT_NM">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
			<xs:minLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UL_NM">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
			<xs:minLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BUD_NOM">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="KORP_OFF_NOM">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="KOD_OBL">
		<xs:restriction base="xs:decimal">
			<xs:pattern value="\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DOC_SERIYA">
		<xs:restriction base="xs:string">
			<xs:pattern value="[АБВГДЕЄЖЗИ_КЛМНОПРСТУФХЦЧШЩЮЯ]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DOC_NOMER">
		<xs:restriction base="xs:decimal">
			<xs:pattern value="\d{6}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--(тип NAZVA_TYPE) - Відомості про документ, що посвідчує фізичну особу.-->
	<xs:complexType name="NAZVA_TYPE">
		<xs:sequence>
			<!-- Зазначається  код  за  ЄДРПОУ  (для   іноземних юридичних осіб зазначається ідентифікаційний код із легалізованого 
                  витягу з  торговельного,  банківського  чи  судового  реєстру  або реєстраційного   посвідчення   місцевого  органу  влади
                  іноземної держави про реєстрацію юридичної особи)  або  реєстраційний  номер облікової картки.
                  Якщо немає коду, то ставиться цифра нуль.
            -->
			<xs:element name="NT_COD" type="ID_OSOBU"/>
			<!--Прізвище/найменування. Для юридичної особи зазначається повне найменування; для фізичної особи зазначається прізвище-->
			<xs:element name="NT_NM1" type="LNAME"/>
			<!--Ім’я/скорочене найменування. Для юридичної особи зазначається скорочене найменування; для фізичної особи зазначається ім’я-->
			<xs:element name="NT_NM2" type="NAME"/>
			<!--По батькові. Зазначається для фізичної особи (за наявності)-->
			<xs:element name="NT_NM3" type="OTCHESTVO" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	<!--(тип PASS_TYPE) - Відомості про документ, що посвідчує фізичну особу.-->
	<xs:complexType name="PASS_TYPE">
		<xs:sequence>
			<!--Серія паспорта. Під час заповнення використовуються великі літери.-->
			<xs:element name="PS_SR" type="DOC_SERIYA"/>
			<!--Номер паспорта.-->
			<xs:element name="PS_NM" type="DOC_NOMER"/>
			<!--Дата видачі паспорта.-->
			<xs:element name="PS_DT" type="DGDate"/>
			<!--Повне найменування органу, який видав паспорт.-->
			<xs:element name="PS_ORG" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<!--(тип ADR_TYPE).Місцезнаходження або місце проживання.-->
	<xs:complexType name="ADR_TYPE">
		<xs:sequence>
			<!--Код країни реєстрації або громадянства. Зазначається цифровий код країни згідно з Класифікацією країн світу -->
			<xs:element name="ADR_COD_KR" type="COD_STR"/>
			<!--Поштовий індекс-->
			<xs:element name="ADR_INDEX" type="COD_INDEX"/>
			<!--Назва населеного пункту-->
			<xs:element name="ADR_PUNKT" type="PUNKT_NM"/>
			<!--Назва вулиці-->
			<xs:element name="ADR_UL" type="UL_NM"/>
			<!--Будинок (номер)-->
			<xs:element name="ADR_BUD" type="BUD_NOM"/>
			<!--Корпус (споруда)-->
			<xs:element name="ADR_KORP" type="KORP_OFF_NOM" nillable="true" minOccurs="0"/>
			<!--Офіс або квартира (номер)-->
			<xs:element name="ADR_OFF" type="KORP_OFF_NOM" nillable="true" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!--(тип UCHAST_TYPE) Пряма участь.-->
	<xs:complexType name="UCHAST_TYPE">
		<xs:sequence>
			<!--Відсотки у статутному капіталі банку-->
			<xs:element name="UT_VIDSOTOK">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="5"/>
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!--Номінал у статутному капіталі банку-->
			<xs:element name="UT_NOMINAL">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!--Кількість голосів-->
			<xs:element name="UT_GOLOSI">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GOLOS_TYPE">
		<xs:sequence>
			<!--Відсотки у статутному капіталі банку-->
			<xs:element name="GT_VIDSOTOK">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="5"/>
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<!--Кількість голосів-->
			<xs:element name="GT_GOLOS">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--(тип PERE_GOLOS_TYPE) - Інформація про набуття права голосу.-->
	<xs:complexType name="PERE_GOLOS_TYPE">
		<xs:sequence>
			<xs:element name="TO_GL_OSOBA" type="NAZVA_TYPE"/>
			<xs:element name="FROM_GL_OSOBA" type="NAZVA_TYPE"/>
			<xs:element name="GL_NABUT" type="GOLOS_TYPE"/>
			<!--Номер договору, на підставі якого передається голос-->
			<xs:element name="GL_NOMER" type="xs:string"/>
			<!--Дата договору, на підставі якого передається голос-->
			<xs:element name="GL_DT" type="DGDate"/>
			<!--Причина передавання голосу-->
			<xs:element name="GL_PRICH" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ROWNUM" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="999999"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<!--(тип FIO_TYPE) - ПІБ фізичної особи.-->
	<xs:complexType name="FIO_TYPE">
		<xs:sequence>
			<!--для фізичної особи зазначається прізвище-->
			<xs:element name="FIO_NM1" type="LNAME"/>
			<!--для фізичної особи зазначається ім’я-->
			<xs:element name="FIO_NM2" type="NAME"/>
			<!-- По батькові. Зазначається для фізичної особи (за наявності)-->
			<xs:element name="FIO_NM3" type="OTCHESTVO" nillable="true"/>
		</xs:sequence>
	</xs:complexType>
	<!--(тип MAN_BANK_TYPE) - Інформація про керівника банку, що підписав анкету та виконавця.-->
	<xs:complexType name="MAN_BANK_TYPE">
		<xs:sequence>
			<xs:element name="MB_NAZVA" type="FIO_TYPE"/>
			<!--Посада керівника, що підписав анкету -->
			<xs:element name="MB_POS" type="xs:string" nillable="true"/>
			<!--Дата підпису -->
			<xs:element name="MB_DT" type="DGDate"/>
			<!--Прізвище виконавця-->
			<xs:element name="MB_ISP_NAZVA" type="FIO_TYPE"/>
			<!--Номер контактного телефону-->
			<xs:element name="MB_TLF" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
						<xs:minLength value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Oleh16101982/WorkWithPfile/include/P70RXX12.xml
<?xml version="1.0" encoding="windows-1251"?>
<DECLARATION xsi:noNamespaceSchemaLocation="NBU00701.XSD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<HEAD>
		<FNAME>P70RXX12.301</FNAME>
		<EDRPOU>12345678</EDRPOU>
		<IDBANK>RXX</IDBANK>
		<MFO>123456</MFO>
		<CDTASK>002</CDTASK>
		<CDSUB>00001</CDSUB>
		<CDFORM>NBU_01SV</CDFORM>
		<FILL_DATE>09.12.2013</FILL_DATE>
		<FILL_TIME>0900</FILL_TIME>
		<EI xsi:nil="true"/>
		<KU>24</KU>
	</HEAD>
	<INF_DT>01.12.2013</INF_DT>
	<TABLE_PIC>UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi</TABLE_PIC>
	<PICTURE>UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi</PICTURE>
	<OWNER ROWNUM="1">
		<OWNER_TYPE>1</OWNER_TYPE>
		<OWNER_NAZVA>
			<NT_COD>0</NT_COD>
			<NT_NM1>онбме мюилемсбюммъ чп.нянах</NT_NM1>
			<NT_NM2>яйнпнвеме мюилемсбюммъ чп.нянах</NT_NM2>
			<NT_NM3 xsi:nil="true"/>
		</OWNER_NAZVA>
		<OWNER_OZN>20</OWNER_OZN>
		<OWNER_POS xsi:nil="true"/>
		<OWNER_ADR>
			<ADR_яOD_KR>100</ADR_яOD_KR>
			<ADR_INDEX>11111</ADR_INDEX>
			<ADR_PUNKT>л╡ярн онкрюбю</ADR_PUNKT>
			<ADR_UL>бскхжъ жемрпюкэмю</ADR_UL>
			<ADR_BUD>14</ADR_BUD>
			<ADR_KORP>ю</ADR_KORP>
			<ADR_OFF xsi:nil="true"/>
		</OWNER_ADR>
		<OWNER_PASS xsi:nil="true"/>
		<OWNER_DATE xsi:nil="true"/>
		<OWNER_DORG xsi:nil="true"/>
		<PR_UCH>
			<UT_VIDSOTOK>23.12</UT_VIDSOTOK>
			<UT_NOMINAL>1234567891267</UT_NOMINAL>
			<UT_GOLOSI>1234</UT_GOLOSI>
		</PR_UCH>
		<OPR_UCH>
			<UT_VIDSOTOK>12.12</UT_VIDSOTOK>
			<UT_NOMINAL>1234567</UT_NOMINAL>
			<UT_GOLOSI>891</UT_GOLOSI>
		</OPR_UCH>
		<GOL_UCH>
			<GT_VIDSOTOK>3.00</GT_VIDSOTOK>
			<GT_GOLOS>123</GT_GOLOS>
		</GOL_UCH>
		<ZAG_UCH>
			<GT_VIDSOTOK>37.24</GT_VIDSOTOK>
			<GT_GOLOS>2248</GT_GOLOS>
		</ZAG_UCH>
	</OWNER>
	<OWNER ROWNUM="2">
		<OWNER_TYPE>2</OWNER_TYPE>
		<OWNER_NAZVA>
			<NT_COD>2200000000</NT_COD>
			<NT_NM1>яхднпемйн</NT_NM1>
			<NT_NM2>яхднп</NT_NM2>
			<NT_NM3>яхднпнбхв</NT_NM3>
		</OWNER_NAZVA>
		<OWNER_OZN>21</OWNER_OZN>
		<OWNER_POS>дхпейрнп</OWNER_POS>
		<OWNER_ADR>
			<ADR_яOD_KR>100</ADR_яOD_KR>
			<ADR_INDEX>99999</ADR_INDEX>
			<ADR_PUNKT>л╡ярн кэб╡б</ADR_PUNKT>
			<ADR_UL>бскхжъ гюрхьмю</ADR_UL>
			<ADR_BUD>15</ADR_BUD>
			<ADR_KORP xsi:nil="true"/>
			<ADR_OFF>12</ADR_OFF>
		</OWNER_ADR>
		<OWNER_PASS>
			<PS_SR>ям</PS_SR>
			<PS_NM>654321</PS_NM>
			<PS_DT>19.02.2004</PS_DT>
			<PS_ORG>оНБМЕ МЮИЛЕМСБЮММЪ НПЦЮМС, ЪЙХИ БХДЮБ ДНЙСЛЕМР</PS_ORG>
		</OWNER_PASS>
		<OWNER_DATE>05.10.1988</OWNER_DATE>
		<OWNER_DORG xsi:nil="true"/>
		<PR_UCH>
			<UT_VIDSOTOK>3.12</UT_VIDSOTOK>
			<UT_NOMINAL>4567</UT_NOMINAL>
			<UT_GOLOSI>4</UT_GOLOSI>
		</PR_UCH>
		<OPR_UCH>
			<UT_VIDSOTOK>1.00</UT_VIDSOTOK>
			<UT_NOMINAL>12</UT_NOMINAL>
			<UT_GOLOSI>1</UT_GOLOSI>
		</OPR_UCH>
		<GOL_UCH>
			<GT_VIDSOTOK>58.64</GT_VIDSOTOK>
			<GT_GOLOS>58</GT_GOLOS>
		</GOL_UCH>
		<ZAG_UCH>
			<GT_VIDSOTOK>62.76</GT_VIDSOTOK>
			<GT_GOLOS>62</GT_GOLOS>
		</ZAG_UCH>
	</OWNER>
	<PERE_GOLOS ROWNUM="1">
		<TO_GL_OSOBA>
			<NT_COD>1111000000</NT_COD>
			<NT_NM1>нянаю, ъй╡и оепедюкх опюбн цнкняс</NT_NM1>
			<NT_NM2>чп.няняаю</NT_NM2>
			<NT_NM3 xsi:nil="true"/>
		</TO_GL_OSOBA>
		<FROM_GL_OSOBA>
			<NT_COD>0</NT_COD>
			<NT_NM1>нянаю, ъйю оепедюкю опюбн цнкняс - оерпнб</NT_NM1>
			<NT_NM2>оерпн</NT_NM2>
			<NT_NM3>оерпнбхв</NT_NM3>
		</FROM_GL_OSOBA>
		<GL_NABUT>
			<GT_VIDSOTOK>28.00</GT_VIDSOTOK>
			<GT_GOLOS>234</GT_GOLOS>
		</GL_NABUT>
		<GL_NOMER>дп-102</GL_NOMER>
		<GL_DT>17.04.2009</GL_DT>
		<GL_PRICH>оПХВХМЮ ОЕПЕДЮБЮММЪ ЦНКНЯС</GL_PRICH>
	</PERE_GOLOS>
	<PERE_GOLOS ROWNUM="2">
		<TO_GL_OSOBA>
			<NT_COD>10000000</NT_COD>
			<NT_NM1>╡бюмнб</NT_NM1>
			<NT_NM2>╡бюм</NT_NM2>
			<NT_NM3>╡бюмнбхв</NT_NM3>
		</TO_GL_OSOBA>
		<FROM_GL_OSOBA>
			<NT_COD>90000000</NT_COD>
			<NT_NM1>нянаю, ъйю оепедюкю опюбн цнкняс - бкюяемйн</NT_NM1>
			<NT_NM2>бюяхк╡и</NT_NM2>
			<NT_NM3>бюяхкэнбхв</NT_NM3>
		</FROM_GL_OSOBA>
		<GL_NABUT>
			<GT_VIDSOTOK>31.00</GT_VIDSOTOK>
			<GT_GOLOS>45671</GT_GOLOS>
		</GL_NABUT>
		<GL_NOMER>дп-345</GL_NOMER>
		<GL_DT>10.02.2008</GL_DT>
		<GL_PRICH>оПХВХМЮ ОЕПЕДЮБЮММЪ ЦНКНЯС</GL_PRICH>
	</PERE_GOLOS>
	<SUM_BANK>
		<GT_VIDSOTOK>111.11</GT_VIDSOTOK>
		<GT_GOLOS>1000000000</GT_GOLOS>
	</SUM_BANK>
	<MAN_BANK>
		<MB_NAZVA>
			<FIO_NM1>йнмдпюремйн</FIO_NM1>
			<FIO_NM2>опнунп</FIO_NM2>
			<FIO_NM3>╡бюмнбхв</FIO_NM3>
		</MB_NAZVA>
		<MB_POS>гюярсомхй цнкнбх</MB_POS>
		<MB_DT>01.08.2008</MB_DT>
		<MB_ISP_NAZVA>
			<FIO_NM1>юмрнмъм</FIO_NM1>
			<FIO_NM2>бюяхк╡и</FIO_NM2>
			<FIO_NM3>оерпнбхв</FIO_NM3>
		</MB_ISP_NAZVA>
		<MB_TLF>+380442520000</MB_TLF>
	</MAN_BANK>
</DECLARATION>
